### ISSUE TITLE
White panels for Material Theme Darker?

### ISSUE THREAD

**Issue by petergoes** [equinusocio/material-theme-white-panels#1]
I really love this theme! And I absolutely love this addon. However, I am using the Darker version of the theme and I could not activate the white panels in that version. Is it possible to create a white panels addon for the darker version?

Thanks in advance

**Comment by equinusocio** [comment]
Not at the moment :) It would no longer be " darker "

**Comment by petergoes** [comment]
Alright, and what about a "darker" version of the White Panels? A Grey Panels if you will.
I am just looking for a way to have a higher contrast between the text editor and the panels. This plugin seems to be doing exactly that

**Comment by equinusocio** [comment]
Done. https://github.com/equinusocio/material-theme-white-panels/releases/tag/v1.0.2
Now you have to wait 1h to get the package control update.

**Comment by petergoes** [comment]
Awesome! Thank you!
