### ISSUE TITLE
Package not found in Package Control

### ISSUE THREAD

**Issue by DisasterMan78** [equinusocio/material-theme-white-panels#11]
**Expected Behaviour**
Typing 'material theme white panels' into Install Package dialogue shows the package which can be clicked to install

**Actual Behaviour**
No results shown

**Suggested Solutions**
1. Contact Package Control to resolve issue
2. Provide manual installation instructions

**Comment by equinusocio** [comment]
https://packagecontrol.io/packages/Material%20Theme%20-%20White%20Panels

**Comment by DisasterMan78** [comment]
Oh I hate myself - wasn't showing up because it was already installed. Just not active...

Sorry. Feel free to point at me and laugh.
