### ISSUE TITLE
Add description of what this actually is?

### ISSUE THREAD

**Issue by rawrmonstar** [equinusocio/material-theme-white-panels#2]
Hi, it would be great if there is some description of what this addon actually does.  What are white panels?  Does it affect the theme or something else?  Maybe add a screenshot?

**Comment by rawrmonstar** [comment]
I've figured it out after installing and messing around... here is a screenshot if other people don't know: 
![image](https://cloud.githubusercontent.com/assets/13814048/12206561/73d7b2a0-b5f6-11e5-9209-1404ee8c9ac3.png)

**Comment by wensonsmith** [comment]
@rawrmonstar  Thank you !!  Your screenshot help me !
