### ISSUE TITLE
Contrast for matched text in command pallete

### ISSUE THREAD

**Issue by enmanuelr** [equinusocio/material-theme-white-panels#3]
On windows, I'm having a problem where the contrast between the matched text and the background is too low. Makes it difficult to read. Perhaps if the background selection color were darker, this could be mitigated.

![untitled](https://cloud.githubusercontent.com/assets/643014/14640545/0924cf6e-0610-11e6-9c23-f7f42622c8c5.png)

I love this theme! Thanks for the contribution.

**Comment by DarthRL** [comment]
Try going to your 
`\Data\Packages\Material Theme - White Panels\Material-Theme.sublime-theme` line 54 & 60
and change the value to `[96, 125, 139]`
maybe do the same to `Material-Theme-Darker.sublime-theme`
AND ENJOY!
