### ISSUE TITLE
Exclude Search field

### ISSUE THREAD

**Issue by katerlouis** [equinusocio/material-theme-white-panels#4]
Is it possible to use white labels only for the command palette and not the search field?

I'd like the panel shown in the screenshot to be styled like the default version of Material Theme. 
Thanks!

<img width="281" alt="b079a00d-c3db-40eb-a1e7-361e3aad700f" src="https://cloud.githubusercontent.com/assets/1983382/15646071/1665d71a-265c-11e6-9404-32407f21ca88.png">

**Comment by katerlouis** [comment]
Too bad :'(

**Comment by equinusocio** [comment]
Atm i can't do this because i need some python logic.
