### ISSUE TITLE
Some visual issues–

### ISSUE THREAD

**Issue by katerlouis** [equinusocio/material-theme-white-panels#5]
1) There is a weird padding at the bottom of the input field. But only if there is one line?

2) Can the background of the search options etc. be in contrast mode also? 

<img width="393" alt="e69d516f-2717-4b5a-af77-510ade3ef20e" src="https://cloud.githubusercontent.com/assets/1983382/15645430/97da47b2-2658-11e6-8db9-df4c6e537e3e.png">

3) Can the padding of the list items be reduced? Atleast vertically? 
4) How can I change the height of the list so more items fit in, maybe responsively regarding on the number of items?

<img width="519" alt="6b6d6fbd-1fdf-41f4-800d-8ea256911bb7" src="https://cloud.githubusercontent.com/assets/1983382/15645494/1b4e95b2-2659-11e6-98ec-fa98a6eff6e4.png">

**Comment by equinusocio** [comment]
I can fix the input padding and add a settings to exclude the input but i can't change the padding because is defined by Material Theme and follows the Material Theme specs.

**Comment by katerlouis** [comment]
"Where there is a will"– ;)

Material theme is so freaking awesome; but in this particular case it is a drawback compared to the vanilla version: less items in sight without scrolling and almost always one option gets "chopped off" by default.

In my opionion that usability drawback would be worth a "new padding in the specs".

But if that's surely off the table, what about the following to see more items:
adjusting the height of the surrounding box. 

When there are only 2 items the box already adjusts and gets smaller. That in the other direction would be awesome.

**Comment by equinusocio** [comment]
I can't do anything of this. The theme is a json file, no logic allowed.

**Comment by equinusocio** [comment]
Not planned
